name: CI

on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout
      - name: UseNodeJS
        uses: actions/setup-node@v1
      - run: npm ci 
      - run: npm test -- --coverage
        env:
          CI: true